import fs from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import config from '../config.js';
import { run, pathExists, userIds } from './sys.js';
import { logger } from './log.js';
import { phpBin, createDatabase, createRedisUser } from './stack.js';

// ============================================================
//  wp.js — WordPress on a wcloud site (s = the site spec, see sites.js)
// ============================================================
// wp-cli always runs as the SITE's user with the site's PHP version, never as
// root or a shared account: a plugin's code executed by wp-cli can then do no
// more than the site's own PHP could.

const root = (s) => `${config.wwwDir}/${s.domain}`;
const htdocs = (s) => `${root(s)}/htdocs`;
const tmp = (s) => `${root(s)}/tmp`;

// wp-cli runner bound to a site:  const wp = await wpCli(helpers, s); await wp(['core', 'version'])
export async function wpCli(helpers, s) {
  const { uid, gid } = await userIds(s.user);
  const as = { uid, gid, home: tmp(s) }; // $HOME must be writable for wp-cli's cache
  return (args, extra = {}) => run(helpers, phpBin(s.php), ['/usr/local/bin/wp', `--path=${htdocs(s)}`, ...args], {
    cwd: htdocs(s), as, env: { WP_CLI_CACHE_DIR: `${tmp(s)}/.wp-cli-cache` }, ...extra,
  });
}

const secret = (n = 24) => randomBytes(n).toString('hex');
// Salts: base64 is safe inside a single-quoted PHP string.
const salt = () => randomBytes(48).toString('base64');

// Table prefixes come from imported archives: only a plain identifier may be
// written into wp-config.php (anything else would be PHP code in the file).
export const safePrefix = (p) => (/^[A-Za-z0-9_]{1,32}$/.test(p || '') ? p : null);

// Database + Redis user + wp-config.php (one level above htdocs, 0600, owned by
// the site), then — unless restoring an archive — download and install core.
//   opts: { adminUser, adminPassword, install = true, tablePrefix = 'wp_' }
export async function setupWordPress(helpers, s, { adminUser, adminPassword, install = true, tablePrefix = 'wp_' } = {}) {
  const { ok, warn } = logger(helpers);
  const dbPass = secret();
  await createDatabase(helpers, s.user, dbPass);
  const redisPass = secret();
  const redis = s.redisDb ? await createRedisUser(helpers, s.user, redisPass, s.redisDb) : false;
  if (!redis) warn('Redis is not available for this site — the object cache stays off.');

  const q = (v) => `'${v}'`; // every value here is hex/base64/identifier — no quotes to escape
  const lines = [
    '<?php',
    '// Generated by wcloud for this site. Safe to edit; wcloud does not rewrite it.',
    `define( 'DB_NAME', ${q(s.user)} );`,
    `define( 'DB_USER', ${q(s.user)} );`,
    `define( 'DB_PASSWORD', ${q(dbPass)} );`,
    "define( 'DB_HOST', 'localhost' );",
    "define( 'DB_CHARSET', 'utf8mb4' );",
    "define( 'DB_COLLATE', '' );",
    '',
    ...['AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT']
      .map((k) => `define( '${k}', ${q(salt())} );`),
    '',
    ...(redis ? [
      '// Redis object cache (activate the "Redis Object Cache" plugin to use it).',
      '// This login can only reach this site\'s own database and keys.',
      `define( 'WP_REDIS_DATABASE', ${s.redisDb} );`,
      `define( 'WP_REDIS_PREFIX', ${q(`${s.user}:`)} );`,
      `define( 'WP_REDIS_PASSWORD', [ ${q(s.user)}, ${q(redisPass)} ] );`,
      '',
    ] : []),
    "define( 'FS_METHOD', 'direct' );",
    "define( 'WP_DEBUG', false );",
    `$table_prefix = ${q(safePrefix(tablePrefix) || 'wp_')};`,
    '',
    "if ( ! defined( 'ABSPATH' ) ) {",
    "\tdefine( 'ABSPATH', __DIR__ . '/htdocs/' );",
    '}',
    "require_once ABSPATH . 'wp-settings.php';",
    '',
  ];
  const cfg = `${root(s)}/wp-config.php`;
  const { uid, gid } = await userIds(s.user);
  await fs.writeFile(cfg, lines.join('\n'), { mode: 0o600 });
  await fs.chown(cfg, uid, gid);
  ok('Database and configuration created');
  if (!install) return;

  const wp = await wpCli(helpers, s);
  const dl = await wp(['core', 'download'], { timeout: 300_000 });
  if (dl.code !== 0) throw new Error('WordPress could not be downloaded — check that this server can reach wordpress.org.');
  // No password on argv (readable by every local user via /proc): --prompt
  // reads it from stdin. Without one requested, a random one is set — the
  // owner sets their own with "Reset password".
  const user = adminUser || 'admin';
  const inst = await wp(['core', 'install', `--url=http://${s.domain}`, `--title=${s.domain}`,
    `--admin_user=${user}`, `--admin_email=admin@${s.domain}`, '--skip-email', '--prompt=admin_password'],
  { stdin: `${adminPassword || secret(16)}\n`, timeout: 120_000 });
  if (inst.code !== 0) throw new Error('WordPress could not be installed.');
  ok(`WordPress installed — administrator: ${user}`);
}

// Set a WP user's password without it ever reaching argv (see setupWordPress).
export async function wpSetPassword(helpers, s, user, password) {
  return (await wpCli(helpers, s))(['user', 'update', user, '--prompt=user_pass'], { stdin: `${password}\n` });
}

// WordPress stores its address absolutely (home/siteurl). When that disagrees
// with what nginx serves, the two bounce the browser between them and the site
// dies with ERR_TOO_MANY_REDIRECTS:
//   • scheme — HTTPS enabled but home is still http:// (nginx forces https,
//     WordPress forces http), or HTTPS turned off while home is https://
//   • host   — nginx redirects www → non-www while home says www (or vice versa)
// So WP must be re-pinned whenever either changes (sites.syncWpAddress). Omitted
// parts keep their current value — except a host that isn't this site's at all
// (a clone still pointing at its source), which becomes the site's domain.
export async function pinWpUrls(helpers, s, { scheme, host } = {}) {
  const { ok, warn } = logger(helpers);
  const wp = await wpCli(helpers, s);
  const cur = await wp(['option', 'get', 'home'], { quiet: true, timeout: 60_000 });
  const m = (cur.stdout || '').trim().match(/^(https?):\/\/([^/]+)/i);
  if (cur.code !== 0 && !m) {
    warn('Could not read the WordPress address — skipping (is WordPress installed here?)');
    return false;
  }
  const own = m && [s.domain, `www.${s.domain}`].includes(m[2].toLowerCase()) ? m[2] : s.domain;
  const url = `${scheme || m?.[1] || 'http'}://${host || own}`;
  if (m && `${m[1]}://${m[2]}` === url) return true; // already correct

  let allOk = true;
  for (const key of ['home', 'siteurl']) {
    const r = await wp(['option', 'update', key, url], { timeout: 60_000 });
    if (r.code !== 0) allOk = false;
  }
  if (allOk) ok(`WordPress address set to ${url}`);
  else warn(`Could not update the WordPress address to ${url}. If the site shows a redirect loop, set it manually under Settings → General.`);
  return allOk;
}

// Page cache (WP Rocket, when active; its files on disk otherwise) + object cache.
export async function clearWpCaches(helpers, s) {
  const wp = await wpCli(helpers, s);
  const rocket = await wp([
    'eval',
    'if (function_exists("rocket_clean_domain")) { rocket_clean_domain(); echo "WP Rocket cache cleared"; } else { echo "WP Rocket not active"; }',
  ]);
  if (rocket.code !== 0) {
    // Remove the cached pages as the site's user (never as root inside a
    // directory the site controls).
    for (const dir of [`${htdocs(s)}/wp-content/cache/wp-rocket`, `${htdocs(s)}/app/cache/wp-rocket`]) {
      if (await pathExists(dir)) await run(helpers, 'find', [dir, '-mindepth', '1', '-delete'], { as: { ...(await userIds(s.user)), home: tmp(s) }, quiet: true, timeout: 120_000 });
    }
  }
  const flush = await wp(['cache', 'flush'], { quiet: true });
  return { rocketOk: rocket.code === 0, objectFlushed: flush.code === 0 };
}

// WordPress core version, or null when this isn't a readable WordPress install.
export async function readWpVersion(helpers, s) {
  if (s.type !== 'wordpress' || !(await pathExists(`${htdocs(s)}/wp-load.php`))) return null;
  const r = await (await wpCli(helpers, s))(['core', 'version'], { timeout: 30_000 });
  if (r.code !== 0) return null;
  const v = (r.stdout || '').trim().split(/\s+/).filter(Boolean).pop() || '';
  return /^\d+\.\d+(\.\d+)?$/.test(v) ? v : null;
}

// DB credentials, read live from wp-config.php (the file is the source of
// truth — nothing is stored). The admin password can't be read back: WordPress
// keeps only a hash (use the resetPassword op).
export async function readDbCredentials(helpers, s) {
  if (s.type !== 'wordpress' || !(await pathExists(`${htdocs(s)}/wp-load.php`))) return null;
  const wp = await wpCli(helpers, s);
  const [name, user, pass] = await Promise.all(
    ['DB_NAME', 'DB_USER', 'DB_PASSWORD'].map((k) => wp(['config', 'get', k], { quiet: true }))
  );
  if (name.code !== 0) return null;
  return {
    db_name: name.stdout.trim(),
    db_user: user.code === 0 ? user.stdout.trim() : '',
    db_password: pass.code === 0 ? pass.stdout.trim() : '',
  };
}
